spring:
  datasource:
    url: jdbc:h2:mem:apialunos
    username: alunos
    password: alunos
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update